export const particleConfig = {
	composition: 'source-over',
	count: 162,
	speed: 0.01,
	parallax: 5.6,
	direction: 220,
	xVariance: 2,
	yVariance: 2,
	rotate: false,
	rotation: 1,
	alphaSpeed: 10,
	alphaVariance: 1,
	minAlpha: 0,
	maxAlpha: 1,
	minSize: 1,
	maxSize: 85,
	style: 'fill',
	bounce: false,
	drift: 0.1,
	glow: 1,
	twinkle: false,
	shape: 'image',
	imageUrl: null,
};
