import Head from 'next/head';

export const Home = () => (
	<div>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<h1>Home</h1>
	</div>
);
